version: "3.8"

services:
  app:
    build: .
    image: app:latest
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && python manage.py runserver"
    volumes:
      - .:/usr/src/app
    expose:
      - "8000"
    networks:
      - main
    restart: on-failure

networks:
  main:
